"""Añadida ForeignKey en Cuentas a Usuario

Revision ID: 0333f9488ac3
Revises: aa3a92ce6c84
Create Date: 2026-03-30 21:22:20.631608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0333f9488ac3'
down_revision: Union[str, Sequence[str], None] = 'aa3a92ce6c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('user', 'admin', name='roles').create(op.get_bind())
    op.create_table('Usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('ultima_vez', sa.DateTime(), nullable=False),
    sa.Column('rol', postgresql.ENUM('user', 'admin', name='roles', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Usuarios')),
    sa.UniqueConstraint('alias', name=op.f('uq_Usuarios_alias')),
    sa.UniqueConstraint('id', name=op.f('uq_Usuarios_id'))
    )
    op.add_column('Cuentas', sa.Column('propietario', sa.BigInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_Cuentas_propietario_Usuarios'), 'Cuentas', 'Usuarios', ['propietario'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Cuentas_propietario_Usuarios'), 'Cuentas', type_='foreignkey')
    op.drop_column('Cuentas', 'propietario')
    op.drop_table('Usuarios')
    sa.Enum('user', 'admin', name='roles').drop(op.get_bind())
    # ### end Alembic commands ###
