"""Creada Tabla de Usuarios Permitidos

Revision ID: 211c0855f888
Revises: 39bca51f8a58
Create Date: 2026-04-03 13:13:17.208492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211c0855f888'
down_revision: Union[str, Sequence[str], None] = '39bca51f8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios_Permitidos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Usuarios_Permitidos'))
    )
    op.create_index(op.f('ix_Usuarios_Permitidos_telegram_id'), 'Usuarios_Permitidos', ['telegram_id'], unique=True)
    op.drop_index(op.f('ix_Usuarios_telegram_id'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_telegram_id'), 'Usuarios', ['telegram_id'], unique=False)
    op.create_foreign_key(op.f('fk_Usuarios_telegram_id_Usuarios_Permitidos'), 'Usuarios', 'Usuarios_Permitidos', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Usuarios_telegram_id_Usuarios_Permitidos'), 'Usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_Usuarios_telegram_id'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_telegram_id'), 'Usuarios', ['telegram_id'], unique=True)
    op.drop_index(op.f('ix_Usuarios_Permitidos_telegram_id'), table_name='Usuarios_Permitidos')
    op.drop_table('Usuarios_Permitidos')
    # ### end Alembic commands ###
