"""Cambiado el nombre de las cuentas a unique=False

Revision ID: 39bca51f8a58
Revises: a9edbc282fc2
Create Date: 2026-03-31 20:39:31.606392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bca51f8a58'
down_revision: Union[str, Sequence[str], None] = 'a9edbc282fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_Cuentas_nombre'), 'Cuentas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_Cuentas_nombre'), 'Cuentas', ['nombre'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
