"""Modificada la Tabla de Usuarios Permitidos y Usuarios

Revision ID: 5c201e0f4d17
Revises: 211c0855f888
Create Date: 2026-04-04 10:18:40.097003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c201e0f4d17'
down_revision: Union[str, Sequence[str], None] = '211c0855f888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('id_permitido', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_Usuarios_telegram_id'), table_name='Usuarios')
    op.drop_constraint(op.f('fk_Usuarios_telegram_id_Usuarios_Permitidos'), 'Usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', 'Usuarios_Permitidos', ['id_permitido'], ['id'])
    op.drop_column('Usuarios', 'telegram_id')
    op.drop_column('Usuarios', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('Usuarios', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Usuarios_telegram_id_Usuarios_Permitidos'), 'Usuarios', 'Usuarios_Permitidos', ['telegram_id'], ['telegram_id'])
    op.create_index(op.f('ix_Usuarios_telegram_id'), 'Usuarios', ['telegram_id'], unique=False)
    op.drop_column('Usuarios', 'id_permitido')
    # ### end Alembic commands ###
