"""Añadiendo la Columna Tipo a las transacciones

Revision ID: 980ace4cdc4b
Revises: ced3856ccdb1
Create Date: 2026-03-16 21:10:08.100903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980ace4cdc4b'
down_revision: Union[str, Sequence[str], None] = 'ced3856ccdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transacciones', sa.Column('tipo', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transacciones', 'tipo')
    # ### end Alembic commands ###
