"""Añadida Columna Telegram_id a la tabla Usuarios

Revision ID: a9edbc282fc2
Revises: 0333f9488ac3
Create Date: 2026-03-30 21:43:05.436920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9edbc282fc2'
down_revision: Union[str, Sequence[str], None] = '0333f9488ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_Usuarios_telegram_id'), 'Usuarios', ['telegram_id'], unique=True)
    op.create_unique_constraint(op.f('uq_Usuarios_id'), 'Usuarios', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_Usuarios_id'), 'Usuarios', type_='unique')
    op.drop_index(op.f('ix_Usuarios_telegram_id'), table_name='Usuarios')
    op.drop_column('Usuarios', 'telegram_id')
    # ### end Alembic commands ###
