"""Mejorada la validación de fechas de transacciones

Revision ID: a9f7811fb39e
Revises: 7fb465a6540b
Create Date: 2026-04-14 22:21:51.805432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f7811fb39e'
down_revision: Union[str, Sequence[str], None] = '7fb465a6540b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cuentas', 'saldo',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('Transacciones', 'monto',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transacciones', 'monto',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('Cuentas', 'saldo',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
