"""Creada Tabla de Usuarios

Revision ID: aa3a92ce6c84
Revises: fcacc1d7dcb5
Create Date: 2026-03-30 21:05:00.389061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3a92ce6c84'
down_revision: Union[str, Sequence[str], None] = 'fcacc1d7dcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
