"""Modificando Fechas de la DB

Revision ID: ced3856ccdb1
Revises: 
Create Date: 2026-03-16 20:40:57.957194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced3856ccdb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cuentas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=4), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Cuentas')),
    sa.UniqueConstraint('nombre', name=op.f('uq_Cuentas_nombre'))
    )
    op.create_table('Transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('etiqueta', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('cuenta', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta'], ['Cuentas.id'], name=op.f('fk_Transacciones_cuenta_Cuentas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Transacciones'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transacciones')
    op.drop_table('Cuentas')
    # ### end Alembic commands ###
