"""Modificada ForeignKey de Usuarios a Usuarios_Permitidos.telegram_id

Revision ID: f552b357012e
Revises: 5c201e0f4d17
Create Date: 2026-04-04 12:18:58.890402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f552b357012e'
down_revision: Union[str, Sequence[str], None] = '5c201e0f4d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', 'Usuarios_Permitidos', ['id_permitido'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Usuarios_id_permitido_Usuarios_Permitidos'), 'Usuarios', 'Usuarios_Permitidos', ['id_permitido'], ['id'])
    # ### end Alembic commands ###
