"""Añadida relationship entre cuentas y transacciones

Revision ID: fcacc1d7dcb5
Revises: 980ace4cdc4b
Create Date: 2026-03-30 11:45:09.045988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcacc1d7dcb5'
down_revision: Union[str, Sequence[str], None] = '980ace4cdc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
